apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-m2uh
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0011-tenant/ci1t-830-0011-app/devfile-sample-m2uh@sha256:6077e3983cfd7fff97fd752779bd45854688ab9a138656761e79cc6144d2c670
        name: my-nodejs
        resources: {}
status: {}
