apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-m2uh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-m2uh
    app.kubernetes.io/part-of: ci1t-830-0011-app
  name: devfile-sample-m2uh
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-m2uh
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-m2uh
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0011-tenant/ci1t-830-0011-app/devfile-sample-m2uh@sha256:6077e3983cfd7fff97fd752779bd45854688ab9a138656761e79cc6144d2c670
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
